// Generated by scripts/generate_cuda_abi.py. Do not edit by hand.
#ifndef BEAMZ_CUDA_ABI_LAYOUT_H_
#define BEAMZ_CUDA_ABI_LAYOUT_H_

#include <cstddef>
#include <cstdint>

namespace beamz::cuda::abi {

inline constexpr int32_t kAbiVersion = 11;
inline constexpr char kPackageVersion[] = "0.11.0";
inline constexpr char kStreamedTarget[] = "beamz_cuda_streamed";
inline constexpr char kProgramTarget[] = "beamz_cuda_program";
inline constexpr char kHopperTarget[] = "beamz_cuda_hopper";

inline constexpr int32_t kProgramLayoutYeeInPlace = 0;
inline constexpr int32_t kProgramLayoutYeeTemporal = 1;
inline constexpr int32_t kProgramLayoutCpmlInPlace = 2;
inline constexpr int32_t kProgramLayoutSourceInPlace = 3;
inline constexpr int32_t kProgramLayoutSourceTemporalCpml = 4;
inline constexpr int32_t kProgramLayoutMonitorInPlace = 5;
inline constexpr int32_t kProgramLayoutMonitorTemporalCpml = 6;

inline constexpr size_t kFieldCount = 6;
inline constexpr size_t kCpmlTermCount = 6;
inline constexpr size_t kSourceGroupCount = 9;
inline constexpr size_t kSourceGroupBufferCount = 3;
inline constexpr size_t kMonitorInputCount = 12;
inline constexpr size_t kYeeGraphInputCount = 24;
inline constexpr size_t kYeeGraphOutputCount = 6;
inline constexpr size_t kCpmlGraphInputCount = 74;
inline constexpr size_t kCpmlGraphOutputCount = 18;
inline constexpr size_t kCpmlPhaseInputCount = 31;
inline constexpr size_t kCpmlEInputOffset = 37;
inline constexpr size_t kCpmlHMetricOffset = 68;
inline constexpr size_t kCpmlEMetricOffset = 71;
inline constexpr size_t kCpmlHPsiInputOffset = 31;
inline constexpr size_t kCpmlEPsiInputOffset = 62;
inline constexpr size_t kTemporalHPsiOutputOffset = 12;
inline constexpr size_t kTemporalEPsiOutputOffset = 18;
inline constexpr size_t kTemporalHPsiWorkspaceOffset = 24;
inline constexpr size_t kTemporalEPsiWorkspaceOffset = 30;
inline constexpr size_t kTemporalFieldWorkspaceInput = 74;
inline constexpr size_t kTemporalPsiWorkspaceInput = 80;

}  // namespace beamz::cuda::abi

#endif
