// Generated by scripts/generate_cuda_abi.py. Do not edit by hand.
#ifndef BEAMZ_CUDA_ABI_LAYOUT_H_
#define BEAMZ_CUDA_ABI_LAYOUT_H_

#include <cstddef>
#include <cstdint>

namespace beamz::cuda::abi {

inline constexpr int32_t kAbiVersion = 10;
inline constexpr char kPackageVersion[] = "0.10.0";
inline constexpr char kStreamedTarget[] = "beamz_cuda_streamed";
inline constexpr char kStreamedStepsTarget[] = "beamz_cuda_streamed_steps";
inline constexpr char kTemporalStepsTarget[] = "beamz_cuda_temporal_steps";
inline constexpr char kStreamedCpmlStepsTarget[] = "beamz_cuda_streamed_cpml_steps";
inline constexpr char kStreamedSourceGroupsCpmlStepsTarget[] = "beamz_cuda_streamed_source_groups_cpml_steps";
inline constexpr char kTemporalSourceGroupsCpmlStepsTarget[] = "beamz_cuda_temporal_source_groups_cpml_steps";
inline constexpr char kTemporalProgramCpmlStepsTarget[] = "beamz_cuda_temporal_program_cpml_steps";
inline constexpr char kStreamedProgramCpmlStepsTarget[] = "beamz_cuda_streamed_program_cpml_steps";
inline constexpr char kHopperTarget[] = "beamz_cuda_hopper";

inline constexpr size_t kFieldCount = 6;
inline constexpr size_t kCpmlTermCount = 6;
inline constexpr size_t kSourceGroupCount = 9;
inline constexpr size_t kSourceGroupBufferCount = 3;
inline constexpr size_t kMonitorInputCount = 12;
inline constexpr size_t kYeeGraphInputCount = 24;
inline constexpr size_t kYeeGraphOutputCount = 6;
inline constexpr size_t kCpmlGraphInputCount = 74;
inline constexpr size_t kCpmlGraphOutputCount = 18;
inline constexpr size_t kCpmlPhaseInputCount = 31;
inline constexpr size_t kCpmlEInputOffset = 37;
inline constexpr size_t kCpmlHMetricOffset = 68;
inline constexpr size_t kCpmlEMetricOffset = 71;
inline constexpr size_t kCpmlHPsiInputOffset = 31;
inline constexpr size_t kCpmlEPsiInputOffset = 62;
inline constexpr size_t kTemporalHPsiOutputOffset = 12;
inline constexpr size_t kTemporalEPsiOutputOffset = 18;
inline constexpr size_t kTemporalHPsiWorkspaceOffset = 24;
inline constexpr size_t kTemporalEPsiWorkspaceOffset = 30;
inline constexpr size_t kTemporalFieldWorkspaceInput = 74;
inline constexpr size_t kTemporalPsiWorkspaceInput = 80;

}  // namespace beamz::cuda::abi

#endif
