"""Generated CUDA FFI contract. Do not edit by hand."""

CUDA_ABI_VERSION = 10
CUDA_PACKAGE_VERSION = "0.10.0"
CUDA_STREAMED_TARGET = "beamz_cuda_streamed"
CUDA_STREAMED_STEPS_TARGET = "beamz_cuda_streamed_steps"
CUDA_TEMPORAL_STEPS_TARGET = "beamz_cuda_temporal_steps"
CUDA_STREAMED_CPML_STEPS_TARGET = "beamz_cuda_streamed_cpml_steps"
CUDA_STREAMED_SOURCE_GROUPS_CPML_STEPS_TARGET = "beamz_cuda_streamed_source_groups_cpml_steps"
CUDA_TEMPORAL_SOURCE_GROUPS_CPML_STEPS_TARGET = "beamz_cuda_temporal_source_groups_cpml_steps"
CUDA_TEMPORAL_PROGRAM_CPML_STEPS_TARGET = "beamz_cuda_temporal_program_cpml_steps"
CUDA_STREAMED_PROGRAM_CPML_STEPS_TARGET = "beamz_cuda_streamed_program_cpml_steps"
CUDA_HOPPER_TARGET = "beamz_cuda_hopper"

CUDA_STREAMED_TARGETS = frozenset((
    CUDA_STREAMED_TARGET,
    CUDA_STREAMED_STEPS_TARGET,
    CUDA_TEMPORAL_STEPS_TARGET,
    CUDA_STREAMED_CPML_STEPS_TARGET,
    CUDA_STREAMED_SOURCE_GROUPS_CPML_STEPS_TARGET,
    CUDA_TEMPORAL_SOURCE_GROUPS_CPML_STEPS_TARGET,
    CUDA_TEMPORAL_PROGRAM_CPML_STEPS_TARGET,
    CUDA_STREAMED_PROGRAM_CPML_STEPS_TARGET,
))

FIELD_COUNT = 6
CPML_TERM_COUNT = 6
SOURCE_GROUP_COUNT = 9
SOURCE_GROUP_BUFFER_COUNT = 3
MONITOR_INPUT_COUNT = 12
YEE_GRAPH_INPUT_COUNT = 24
YEE_GRAPH_OUTPUT_COUNT = 6
CPML_GRAPH_INPUT_COUNT = 74
CPML_GRAPH_OUTPUT_COUNT = 18
CPML_PHASE_INPUT_COUNT = 31
CPML_E_INPUT_OFFSET = 37
CPML_H_METRIC_OFFSET = 68
CPML_E_METRIC_OFFSET = 71
CPML_H_PSI_INPUT_OFFSET = 31
CPML_E_PSI_INPUT_OFFSET = 62
TEMPORAL_H_PSI_OUTPUT_OFFSET = 12
TEMPORAL_E_PSI_OUTPUT_OFFSET = 18
TEMPORAL_H_PSI_WORKSPACE_OFFSET = 24
TEMPORAL_E_PSI_WORKSPACE_OFFSET = 30
TEMPORAL_FIELD_WORKSPACE_INPUT = 74
TEMPORAL_PSI_WORKSPACE_INPUT = 80
